version: '3.9'

services:
  postgres:
    image: postgres:15 
    container_name: intipa_churin_db
    environment:
      POSTGRES_USER: JosuSTK
      POSTGRES_PASSWORD: admin12345
      POSTGRES_DB: Intipa_Churin # Nombre exacto de tu base de datos actual
    ports:
      - "5432:5432" # Mapeado al puerto estándar para que db.js conecte directo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_intipa_churin
    environment:
      PGADMIN_DEFAULT_EMAIL: josuecruz@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin12345
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always

volumes:
  postgres_data:
  pgadmin_data: